const userJSON= '[{"id":1,"username":"Lavina_Durgan","followers":65368,"pic":"https://s3.us-east-2.amazonaws.com/zluserpics/user_82.jpg","city":"Klockobury","ustate":"New Mexico","country":"Vanuatu","pro_user":0},{"id":2,"username":"Richard.Rohan64","followers":7781,"pic":"https://s3.us-east-2.amazonaws.com/zluserpics/user_8.jpg","city":"Jensenburgh","ustate":"Delaware","country":"Bahrain","pro_user":1},{"id":3,"username":"Jade33","followers":50400,"pic":"https://s3.us-east-2.amazonaws.com/zluserpics/user_69.jpg","city":"Tristintown","ustate":"Louisiana","country":"Bahamas","pro_user":0},{"id":4,"username":"Lexi.Harber","followers":97366,"pic":"https://s3.us-east-2.amazonaws.com/zluserpics/user_49.jpg","city":"Marcosfort","ustate":"Pennsylvania","country":"Iran","pro_user":0},{"id":5,"username":"Dillan_Schultz","followers":65810,"pic":"https://s3.us-east-2.amazonaws.com/zluserpics/user_2.jpg","city":"Bradtketon","ustate":"Florida","country":"India","pro_user":0},{"id":6,"username":"Xavier.Rosenbaum","followers":31266,"pic":"https://s3.us-east-2.amazonaws.com/zluserpics/user_35.jpg","city":"Kiehnstad","ustate":"Pennsylvania","country":"Netherlands Antilles","pro_user":1},{"id":7,"username":"Jerrold46","followers":37439,"pic":"https://s3.us-east-2.amazonaws.com/zluserpics/user_120.jpg","city":"West Reeceshire","ustate":"Minnesota","country":"Faroe Islands","pro_user":0},{"id":8,"username":"Luciano.Koch","followers":86336,"pic":"https://s3.us-east-2.amazonaws.com/zluserpics/user_111.jpg","city":"Beckermouth","ustate":"Nevada","country":"Lithuania","pro_user":1},{"id":9,"username":"Bernadette.Gleichner81","followers":67119,"pic":"https://s3.us-east-2.amazonaws.com/zluserpics/user_79.jpg","city":"West Narciso","ustate":"Maryland","country":"Saint Vincent and the Grenadines","pro_user":1}]';
const playlistJSON = '[{"id":1,"username":"Wendy31","pic":"https://s3.us-east-2.amazonaws.com/zlplaylistpics/playlist_24.jpg","title":"Dolore soluta.","num_likes":82826,"num_reposts":25283,"song_id":1,"user":{"id":80,"username":"Wendy31","followers":36092,"pic":"https://s3.us-east-2.amazonaws.com/zluserpics/user_105.jpg","city":"Jaskolskiberg","ustate":"New Mexico","country":"Dominica","pro_user":0}},{"id":2,"username":"Everardo42","pic":"https://s3.us-east-2.amazonaws.com/zlplaylistpics/playlist_55.jpg","title":"Corporis ea.","num_likes":29386,"num_reposts":34299,"song_id":1,"user":{"id":66,"username":"Everardo42","followers":4866,"pic":"https://s3.us-east-2.amazonaws.com/zluserpics/user_49.jpg","city":"South Letitialand","ustate":"Utah","country":"Greenland","pro_user":1}},{"id":3,"username":"Jaquelin_Hahn18","pic":"https://s3.us-east-2.amazonaws.com/zlplaylistpics/playlist_15.jpg","title":"Et harum.","num_likes":19286,"num_reposts":83199,"song_id":1,"user":{"id":96,"username":"Jaquelin_Hahn18","followers":27275,"pic":"https://s3.us-east-2.amazonaws.com/zluserpics/user_84.jpg","city":"New Lottie","ustate":"Pennsylvania","country":"Hungary","pro_user":1}}]';

const HCDATA = {
  users: JSON.parse(userJSON),
  playlists: JSON.parse(playlistJSON)
};

export default HCDATA;
